export {default as Header} from './header/Header'
export {default as Buttun} from './buttuns/Buttun'
export {default as Login} from './login/Login'
export {default as Input} from './input/Input'
export {default as FormIns} from './form_ins/FormIns'
export {default as Annonce} from './annonce/Annonce'
export {default as SideBar} from './sideBar/SideBar'