export {default as Home} from './home/Home'
export {default as Layout} from './Layout'
export {default as Auth} from './auth/Auth'
export {default as Inscription} from './inscription/Inscription'
export {default as JobSearch} from './jobSearch/JobSearch'
export {default as Apropos} from './apropos/Apropos'