export {default as Home} from './home/Home'
export {default as Layout} from './Layout'
export {default as Search} from './search/Search'
export {default as Auth} from './auth/Auth'
export {default as Inscription} from './inscription/Inscription'